name: CI
on:
  - push
  - pull_request
env:
  NODE_ENV: test
  PORT: 3000
  DB_CONNECTION_URL: mongodb://127.0.0.1:27017/express-starter-test
  WINSTON_TRANSPORTS: console
  WINSTON_TRANSPORTS_CONSOLE_LEVEL: error

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install && pnpm install codecov
      - name: Lint codebase
        run: pnpm lint
      - name: Test codebase
        run: pnpm test
      - name: Code coverage
        run: pnpm coverage-gh
      - name: Upload coverage reports
        uses: codecov/codecov-action@v1
