name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        with:
          version: 7
  
      - name: Install Dependencies
        run: pnpm install && pnpm install codecov

      - name: Lint codebase
        run: pnpm lint

      - name: Test codebase
        run: pnpm test

      - name: Code coverage
        run: pnpm coverage-gh
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v1
